public enum UrlAction{
    ERROR, 
    LOGIN, LOGOUT, 
    PUBLICKEY,
    STUDENT, ALL_STUDENTS, 
    TEACHER, ALL_TEACHERS, 
    USER, NEW_USER, ALL_USERS, DELETE_USER, 
    TASK, NEW_TASK,ALL_TASKS, TASKSTEP, NEW_TASKSTEP, ALL_TASKSTEPS, NEW_PETITION, 
    TASK_ASSIGN, ALL_ASSIGNMENTS,
    TASKITEM, NEW_TASKITEM, ALL_TASKITEMS, DELETE_TASKITEM,
    ITEM, NEW_ITEM,ALL_ITEMS, DELETE_ITEM,
    MEDIA, NEW_MEDIA, ALL_MEDIA, DELETE_MEDIA,
    TEST
}