public enum UrlAction{
    ERROR, 
    LOGIN, LOGOUT, 
    STUDENT, ALL_STUDENTS, 
    TEACHER, ALL_TEACHERS, 
    USER, NEW_USER, ALL_USERS, DELETE_USER, 
    TASK, NEW_TASK,ALL_TASKS, TASKSTEP, NEW_TASKSTEP, ALL_TASKSTEPS, NEW_PETITION, 
    TASKITEM, NEW_TASKITEM, ALL_TASKITEMS, DELETE_TASKITEM,
    ITEM, NEW_ITEM,ALL_ITEMS, DELETE_ITEM
}