public enum UrlAction{
    ERROR, 
    LOGIN, LOGOUT, 
    STUDENT, ALL_STUDENTS, 
    TEACHER, ALL_TEACHERS, 
    USER, NEW_USER, ALL_USERS, DELETE_USER, 
    TASK, NEW_TASK,ALL_TASKS, TASKSTEP, NEW_TASKSTEP, ALL_TASKSTEPS
}